config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('upskill/',include('upskill.urls',namespace='upskill')),
    path('user/',include('user.urls',namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),

] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upskill/urls.py
from django.urls import path
from .views import IndexView,AboutView,CourseView,CourseDetail,ContentDetailView, download_file

app_name = 'upskill'

urlpatterns = [
     path('',IndexView.as_view(),name='index'),
     path('subject/<slug:subject_slug>',IndexView.as_view(),name='courses_of_subject'),
     path('about/',AboutView.as_view(),name='about'),
     path('courses/',CourseView.as_view(),name='courses'),
     path('course/<slug:slug>/detail/',CourseDetail.as_view(),name='detail'),
     path('lesson/<int:pk>/',ContentDetailView.as_view(),name='content_detail'),
     path('content/<int:content_id>/download/',download_file,name='content_file_download'),
]

user/urls.py
from django.urls import path
from .views import register_page,verify_email_confirm
from django.contrib.auth.views import LogoutView


app_name = 'user'

urlpatterns = [
    path('register/',register_page,name='register_page'),
    path('email-confirm/<uidb64>/<token>/',verify_email_confirm,name='verify-email-confirm'),
    path('logout/',LogoutView.as_view(),name='logout')
]

upskill/models.py
from django.db import models
from django.templatetags.static import static

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
# Create your models here.


class Teacher(models.Model):
    full_name = models.CharField(max_length=255)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='instructors/', blank=True, null=True)

    expertise = models.CharField(
        max_length=255,
        help_text="Masalan: Python, Frontend, Data Science"
    )

    experience_years = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name



class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(Teacher,related_name='courses',on_delete=models.SET_NULL,null=True)
    subject = models.ForeignKey(Subject,related_name='courses',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    price = models.DecimalField(max_digits=14,decimal_places=2,default = 0)
    overview = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images',null=True,blank=True)
    
    class Meta:
        ordering = ['-created_at']

    @property
    def get_image_url(self):
        if not self.image:
            return static('upskill/img/no-image/no-image.png')
        return self.image.url
    
    def __str__(self):
        return self.title


class Module(models.Model):
    course = models.ForeignKey(Course,related_name='modules',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    overview = models.TextField(null=True,blank=True)
    
    def __str__(self):
        return self.title


class Content(models.Model):
    module = models.ForeignKey(Module,related_name='contents',on_delete=models.CASCADE)
    
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            "model__in":(
                'text',
                'video',
                'image',
                'file'
            )
        }
    ) #
    
    object_id = models.PositiveIntegerField()

    item = GenericForeignKey(
        'content_type',
        'object_id'
    )
    


class ItemBase(models.Model):
    owner = models.ForeignKey(Teacher,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        abstract = True


class Text(ItemBase):
    content = models.TextField() 
    
class File(ItemBase):
    file = models.FileField(upload_to='files')


class Video(ItemBase):
    url = models.URLField()
    
    @property
    def embed_url(self):
        if "youtube.com/watch?v=" in self.url:
            return self.url.replace("watch?v=", "embed/")
        if "youtu.be/" in self.url:
            return self.url.replace("youtu.be/", "youtube.com/embed/")
        return self.url

class Image(ItemBase):
    image = models.ImageField(upload_to='images')

upskill/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView,TemplateView,DetailView
from .models import Subject,Course,Module, Content


import os
from django.http import FileResponse, Http404
from django.shortcuts import get_object_or_404
from .models import File, Content
# Create your views here.


# def index(request):
#     if request.method == 'POST':
#         pass
    
#     else:
#         pass

#     return render(request,'upskill/index.html')


# class IndexView(View):
    
#     def get(self,request,subject_slug = None):
        
#         if subject_slug is None:
#             subjects = Subject.objects.all()
#         else:
#             pass
    
#         context = {
#             'subjects':subjects.order_by('id')
#         }
        
#         return render(request,'upskill/index.html',context)
    

class IndexView(ListView):
    model = Subject
    template_name = 'upskill/index.html'
    context_object_name = 'subjects'
    ordering = ['id']

    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        subject_slug = self.kwargs.get('subject_slug')
        
        courses = Course.objects.all()
        
        if subject_slug:
            courses = courses.filter(subject__slug = subject_slug)
        
        context['courses'] = courses
        
        
        return context
    
    
class AboutView(TemplateView):
    template_name = 'upskill/about.html'



class CourseView(TemplateView):
    template_name = 'upskill/course.html'
    
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['courses'] = Course.objects.all()
        return context
    
    
class CourseDetail(DetailView):
    template_name = 'upskill/detail.html'
    queryset = Course.objects.all()
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        course = self.get_object()
        context =  super().get_context_data(**kwargs)
        context['modules'] = enumerate(course.modules.all(), start=1)
        return context
    

    

class ContentDetailView(DetailView):
    template_name = 'upskill/content_detail.html'
    context_object_name = 'content'
    model = Content
    



def download_file(request, content_id):
    content = get_object_or_404(Content, id=content_id)

    # faqat file bo‘lsa
    if content.content_type.model != 'file':
        raise Http404("Not a file content")

    file_item = content.item  # bu File model

    file_path = file_item.file.path
    file_name = os.path.basename(file_path)

    response = FileResponse(
        open(file_path, 'rb'),
        as_attachment=True,
        filename=file_name
    )
    return response

upskill/templates/upskill/about.html
{% extends 'upskill/base/base.html' %}
{%load static%}

{%block mainPage%}
    About
{%endblock%}

{%block variablePath%} About {%endblock%}


{%block about_content%}
  

    <!-- About Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-5 mb-5 mb-lg-0" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="img/about.jpg" style="object-fit: cover;">
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="section-title position-relative mb-4">
                        <h6 class="d-inline-block position-relative text-secondary text-uppercase pb-2">About Us</h6>
                        <h1 class="display-4">First Choice For Online Education Anywhere</h1>
                    </div>
                    <p>Tempor erat elitr at rebum at at clita aliquyam consetetur. Diam dolor diam ipsum et, tempor voluptua sit consetetur sit. Aliquyam diam amet diam et eos sadipscing labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor consetetur takimata eirmod, dolores takimata consetetur invidunt magna dolores aliquyam dolores dolore. Amet erat amet et magna</p>
                    <div class="row pt-3 mx-0">
                        <div class="col-3 px-0">
                            <div class="bg-success text-center p-4">
                                <h1 class="text-white" data-toggle="counter-up">123</h1>
                                <h6 class="text-uppercase text-white">Available<span class="d-block">Subjects</span></h6>
                            </div>
                        </div>
                        <div class="col-3 px-0">
                            <div class="bg-primary text-center p-4">
                                <h1 class="text-white" data-toggle="counter-up">1234</h1>
                                <h6 class="text-uppercase text-white">Online<span class="d-block">Courses</span></h6>
                            </div>
                        </div>
                        <div class="col-3 px-0">
                            <div class="bg-secondary text-center p-4">
                                <h1 class="text-white" data-toggle="counter-up">123</h1>
                                <h6 class="text-uppercase text-white">Skilled<span class="d-block">Instructors</span></h6>
                            </div>
                        </div>
                        <div class="col-3 px-0">
                            <div class="bg-warning text-center p-4">
                                <h1 class="text-white" data-toggle="counter-up">1234</h1>
                                <h6 class="text-uppercase text-white">Happy<span class="d-block">Students</span></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Feature Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-7 mb-5 mb-lg-0">
                    <div class="section-title position-relative mb-4">
                        <h6 class="d-inline-block position-relative text-secondary text-uppercase pb-2">Why Choose Us?</h6>
                        <h1 class="display-4">Why You Should Start Learning with Us?</h1>
                    </div>
                    <p class="mb-4 pb-2">Aliquyam accusam clita nonumy ipsum sit sea clita ipsum clita, ipsum dolores amet voluptua duo dolores et sit ipsum rebum, sadipscing et erat eirmod diam kasd labore clita est. Diam sanctus gubergren sit rebum clita amet.</p>
                    <div class="d-flex mb-3">
                        <div class="btn-icon bg-primary mr-4">
                            <i class="fa fa-2x fa-graduation-cap text-white"></i>
                        </div>
                        <div class="mt-n1">
                            <h4>Skilled Instructors</h4>
                            <p>Labore rebum duo est Sit dolore eos sit tempor eos stet, vero vero clita magna kasd no nonumy et eos dolor magna ipsum.</p>
                        </div>
                    </div>
                    <div class="d-flex mb-3">
                        <div class="btn-icon bg-secondary mr-4">
                            <i class="fa fa-2x fa-certificate text-white"></i>
                        </div>
                        <div class="mt-n1">
                            <h4>International Certificate</h4>
                            <p>Labore rebum duo est Sit dolore eos sit tempor eos stet, vero vero clita magna kasd no nonumy et eos dolor magna ipsum.</p>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="btn-icon bg-warning mr-4">
                            <i class="fa fa-2x fa-book-reader text-white"></i>
                        </div>
                        <div class="mt-n1">
                            <h4>Online Classes</h4>
                            <p class="m-0">Labore rebum duo est Sit dolore eos sit tempor eos stet, vero vero clita magna kasd no nonumy et eos dolor magna ipsum.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100" src="img/feature.jpg" style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Feature Start -->

{%endblock%}

upskill/templates/upskill/content_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Content Detail</title>
</head>
<body>

    <style>
   

    .lesson-wrapper {
        background: #e5e7eb;
        border-radius: 16px;
        padding: 24px;
        box-shadow: 0 10px 40px rgba(0,0,0,0.06);
        max-width: 1100px;
        margin: 20px auto;
}

/* HEADER */
.lesson-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 24px;
}

.lesson-title {
    font-size: 26px;
    font-weight: 700;
    color: #1f2937;
    line-height: 1.3;
    border-left: 5px solid #2563eb;
    padding-left: 14px;
}

/* TEACHER */
.lesson-teacher {
    display: flex;
    align-items: center;
    gap: 12px;
    background: #f8fafc;
    padding: 10px 14px;
    border-radius: 12px;
}

.lesson-teacher img {
    width: 46px;
    height: 46px;
    border-radius: 50%;
    object-fit: cover;
}

.teacher-name {
    font-size: 14px;
    font-weight: 600;
    color: #111827;
}

.teacher-role {
    font-size: 12px;
    color: #6b7280;
}

/* VIDEO */
.lesson-video-wrapper {
    margin-top: 16px;
}

.lesson-video iframe {
    border-radius: 16px;
}

/* TEXT */
.lesson-text {
    margin-top: 24px;
    font-size: 16px;
    line-height: 1.8;
    color: #374151;
}

/* FALLBACK */
.lesson-fallback {
    display: inline-block;
    padding: 14px 20px;
    background: #2563eb;
    color: #fff;
    border-radius: 10px;
    text-decoration: none;
    font-weight: 500;
}

.lesson-fallback:hover {
    background: #1d4ed8;
}

</style>
<div class="lesson-wrapper">

    <!-- Header -->
    <div class="lesson-header">
        <div class="lesson-title-box">
            <h2 class="lesson-title">
                {{ content.item.title }}
            </h2>
        </div>

        <div class="lesson-teacher">
            <div>
                <div class="teacher-name">
                    <span style="font-size:20px;">{{ content.item.owner.full_name }}</span>
                </div>
                <div class="teacher-role">
                    <span style="font-size:18px;">Instructor</span>

                </div>
            </div>
        </div>
    </div>

    <!-- Content -->
    {% if content.content_type.model == 'video' %}
        <div class="lesson-video-wrapper">
            {% if content.item.embed_url %}
                <div class="ratio ratio-16x9 lesson-video">
                    <iframe
                        src="{{ content.item.embed_url }}"
                        allowfullscreen
                        loading="lazy">
                    </iframe><br>
                    <span style="font-size:22px; margin-top:20px; display:inline-block; font-weight:300;">
                        Python is a dynamically typed language as opposed to statically typed (like Go, Rust). Python interpreter (responsible for executing Python code) doesn’t necessarily know the types of variables before its execution.
This dynamic nature of Python is both its strength and weakness. Its strength lies in the fact that you don’t have to worry about the type system, enabling you to achieve a lot in less time (e.g., throwaway POC projects). Its weakness, however, affects the longevity of the software (hard to refactor and lacks self-explanatory structure). Type annotations (introduced in Python v3.5) try to bridge the gap and it is often better than having no types. I say tries because, at the end of the, it's a sophisticated linter and has no implications during the runtime.
                    </span>
                </div>
            {% else %}
                <a href="{{ content.item.url }}" target="_blank" class="lesson-fallback">
                    🎥 Videoni YouTube’da ko‘rish
                </a>
            {% endif %}
        </div>
    {% endif %}

    {% if content.content_type.model == 'text' %}
        <div class="lesson-text">
            {{ content.item.content|linebreaks }}
        </div>
    {% endif %}

    {% if content.content_type.model == 'file' %}
        <a href="{% url 'content_file_download' content.id %}"
        class="lesson-fallback"
        style="margin-top:20px;">
            📎 {{ content.item.title }} — Yuklab olish
    </a>
{% endif %}

</div>


</body>
</html>

upskill/templates/upskill/course.html
{% extends 'upskill/base/base.html' %}
{%load static%}

{%block mainPage%}
    Courses
{%endblock%}

{%block variablePath%} Course {%endblock%}

{%block course_content %}
 

    <!-- Courses Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row mx-0 justify-content-center">
                <div class="col-lg-8">
                    <div class="section-title text-center position-relative mb-5">
                        <h6 class="d-inline-block position-relative text-secondary text-uppercase pb-2">Our Courses</h6>
                        <h1 class="display-4">Checkout New Releases Of Our Courses</h1>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for course in courses%}
                    <div class="col-lg-4 col-md-6 pb-4">
                        <a class="courses-list-item position-relative d-block overflow-hidden mb-2" href="{% url 'upskill:detail' course.slug %}">
                            <img class="img-fluid" src="{{course.get_image_url}}" alt="">
                            <div class="courses-text">
                                <h4 class="text-center text-white px-3">{{course.title}}</h4>
                                <div class="border-top w-100 mt-3">
                                    <div class="d-flex justify-content-between p-4">
                                        <span class="text-white"><i class="fa fa-user mr-2"></i>{{course.owner}}</span>
                                        <span class="text-white"><i class="fa fa-star mr-2"></i>4.5
                                            <small>(250)</small></span>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                
                {%endfor%}
            </div>
        </div>
    </div>
    <!-- Courses End -->
{%endblock%}

upskill/templates/upskill/detail.html
{% extends 'upskill/base/base.html' %}
{%load static%}

{%block mainPage%}
    Course Detail
{%endblock%}

{%block variablePath%} Detail {%endblock%}

{%block course_detail%}

    <style>
        .lesson-item {
            cursor: pointer;
        }

        .lesson-item:hover {
            background-color: #f5f8ff;
        }
    </style>
    <!-- Detail Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="mb-5">
                        <div class="section-title position-relative mb-5">
                            <h6 class="d-inline-block position-relative text-secondary text-uppercase pb-2">Course Detail</h6>
                            <h1 class="display-4">{{course.title}}</h1>
                        </div>
                        <img class="img-fluid rounded w-100 mb-4" src="{{course.get_image_url}}" alt="Image">
                        <p>{{course.overview}}</p>

                        <h2 class="mb-4">Modules</h2>
                        <div class="accordion" id="courseModules">
                            {% for index, module in modules %}

                            <div class="card mb-3">

                                <!-- Module header -->
                                <div class="card-header d-flex justify-content-between align-items-center"
                                    data-toggle="collapse"
                                    data-target="#module{{ index }}"
                                    style="cursor: pointer;">
                                    <h6 class="mb-0">
                                        <span class="text-muted mr-2">0{{ index }}</span>
                                        <strong>{{ module.title }}</strong>
                                    </h6>
                                    <i class="fa fa-times text-muted"></i>
                                </div>

                                <!-- Module body -->
                                <div id="module{{ index }}" class="collapse {% if forloop.first %}show{% endif %}"
                                    data-parent="#courseModules">
                                    <div class="card-body">
                                        {% for content in module.contents.all %}
                                            <div class="d-flex justify-content-between align-items-center mb-3 lesson-item">
                                            
                                                <div>
                                                    <i class="fa fa-play-circle text-primary mr-2"></i>
                                                    <a href="{% url 'content_detail' content.id %}">{{ content.item.title }}</a>
                                                </div>
                                                <i class="fa fa-lock text-muted"></i>
                                            </div>
                                        {% empty %}
                                            <p class="text-muted">Hozircha mavzu yo‘q</p>
                                        {% endfor %}

                                    </div>
                                </div>
                            </div>

                            {% endfor %}
                        </div>

                    </div>

                    
               </div>

                <div class="col-lg-4 mt-5 mt-lg-0">
                    <div class="bg-primary mb-5 py-3">
                        <h3 class="text-white py-3 px-4 m-0">Course Features</h3>
                        <div class="d-flex justify-content-between border-bottom px-4">
                            <h6 class="text-white my-3">Instructor</h6>
                            <h6 class="text-white my-3">{{course.owner}}</h6>
                        </div>
                        <div class="d-flex justify-content-between border-bottom px-4">
                            <h6 class="text-white my-3">Rating</h6>
                            <h6 class="text-white my-3">4.5 <small>(250)</small></h6>
                        </div>
                        <div class="d-flex justify-content-between border-bottom px-4">
                            <h6 class="text-white my-3">Lectures</h6>
                            <h6 class="text-white my-3">15</h6>
                        </div>
                        <div class="d-flex justify-content-between border-bottom px-4">
                            <h6 class="text-white my-3">Duration</h6>
                            <h6 class="text-white my-3">10.00 Hrs</h6>
                        </div>
                        <div class="d-flex justify-content-between border-bottom px-4">
                            <h6 class="text-white my-3">Skill level</h6>
                            <h6 class="text-white my-3">All Level</h6>
                        </div>
                        <div class="d-flex justify-content-between px-4">
                            <h6 class="text-white my-3">Language</h6>
                            <h6 class="text-white my-3">English</h6>
                        </div>
                        <h5 class="text-white py-3 px-4 m-0">Course Price: ${{course.price}}</h5>
                        <div class="py-3 px-4">
                            <a class="btn btn-block btn-secondary py-3 px-5" href="">Enroll Now</a>
                        </div>
                    </div>

                    <div class="mb-5">
                        <h2 class="mb-3">Categories</h2>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="" class="text-decoration-none h6 m-0">Web Design</a>
                                <span class="badge badge-primary badge-pill">150</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="" class="text-decoration-none h6 m-0">Web Development</a>
                                <span class="badge badge-primary badge-pill">131</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="" class="text-decoration-none h6 m-0">Online Marketing</a>
                                <span class="badge badge-primary badge-pill">78</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="" class="text-decoration-none h6 m-0">Keyword Research</a>
                                <span class="badge badge-primary badge-pill">56</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                <a href="" class="text-decoration-none h6 m-0">Email Marketing</a>
                                <span class="badge badge-primary badge-pill">98</span>
                            </li>
                        </ul>
                    </div>

                    

                    <div class="mb-5">
                        <h2 class="mb-4">Recent Courses</h2>
                        <a class="d-flex align-items-center text-decoration-none mb-4" href="">
                            <img class="img-fluid rounded" src="img/courses-80x80.jpg" alt="">
                            <div class="pl-3">
                                <h6>Web design & development courses for beginners</h6>
                                <div class="d-flex">
                                    <small class="text-body mr-3"><i class="fa fa-user text-primary mr-2"></i>Jhon Doe</small>
                                    <small class="text-body"><i class="fa fa-star text-primary mr-2"></i>4.5 (250)</small>
                                </div>
                            </div>
                        </a>
                        <a class="d-flex align-items-center text-decoration-none mb-4" href="">
                            <img class="img-fluid rounded" src="img/courses-80x80.jpg" alt="">
                            <div class="pl-3">
                                <h6>Web design & development courses for beginners</h6>
                                <div class="d-flex">
                                    <small class="text-body mr-3"><i class="fa fa-user text-primary mr-2"></i>Jhon Doe</small>
                                    <small class="text-body"><i class="fa fa-star text-primary mr-2"></i>4.5 (250)</small>
                                </div>
                            </div>
                        </a>
                        <a class="d-flex align-items-center text-decoration-none mb-4" href="">
                            <img class="img-fluid rounded" src="img/courses-80x80.jpg" alt="">
                            <div class="pl-3">
                                <h6>Web design & development courses for beginners</h6>
                                <div class="d-flex">
                                    <small class="text-body mr-3"><i class="fa fa-user text-primary mr-2"></i>Jhon Doe</small>
                                    <small class="text-body"><i class="fa fa-star text-primary mr-2"></i>4.5 (250)</small>
                                </div>
                            </div>
                        </a>
                        <a class="d-flex align-items-center text-decoration-none" href="">
                            <img class="img-fluid rounded" src="img/courses-80x80.jpg" alt="">
                            <div class="pl-3">
                                <h6>Web design & development courses for beginners</h6>
                                <div class="d-flex">
                                    <small class="text-body mr-3"><i class="fa fa-user text-primary mr-2"></i>Jhon Doe</small>
                                    <small class="text-body"><i class="fa fa-star text-primary mr-2"></i>4.5 (250)</small>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>


    <!-- Detail End -->
{%endblock%}