config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('upskill/',include('upskill.urls',namespace='upskill')),
    path('user/',include('user.urls',namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),

] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upskill/urls.py
from django.urls import path
from .views import IndexView,AboutView,CourseView,CourseDetail,ContentDetailView, download_file

app_name = 'upskill'

urlpatterns = [
     path('',IndexView.as_view(),name='index'),
     path('subject/<slug:subject_slug>',IndexView.as_view(),name='courses_of_subject'),
     path('about/',AboutView.as_view(),name='about'),
     path('courses/',CourseView.as_view(),name='courses'),
     path('course/<slug:slug>/detail/',CourseDetail.as_view(),name='detail'),
     path('lesson/<int:pk>/',ContentDetailView.as_view(),name='content_detail'),
     path('content/<int:content_id>/download/',download_file,name='content_file_download'),
]

user/urls.py
from django.urls import path
from .views import register_page,verify_email_confirm
from django.contrib.auth.views import LogoutView


app_name = 'user'

urlpatterns = [
    path('register/',register_page,name='register_page'),
    path('email-confirm/<uidb64>/<token>/',verify_email_confirm,name='verify-email-confirm'),
    path('logout/',LogoutView.as_view(),name='logout')
]

upskill/models.py
from django.db import models
from django.templatetags.static import static

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
# Create your models here.


class Teacher(models.Model):
    full_name = models.CharField(max_length=255)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='instructors/', blank=True, null=True)

    expertise = models.CharField(
        max_length=255,
        help_text="Masalan: Python, Frontend, Data Science"
    )

    experience_years = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name



class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    
    class Meta:
        ordering = ['title']
        
    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(Teacher,related_name='courses',on_delete=models.SET_NULL,null=True)
    subject = models.ForeignKey(Subject,related_name='courses',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    price = models.DecimalField(max_digits=14,decimal_places=2,default = 0)
    overview = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images',null=True,blank=True)
    
    class Meta:
        ordering = ['-created_at']

    @property
    def get_image_url(self):
        if not self.image:
            return static('upskill/img/no-image/no-image.png')
        return self.image.url
    
    def __str__(self):
        return self.title


class Module(models.Model):
    course = models.ForeignKey(Course,related_name='modules',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    overview = models.TextField(null=True,blank=True)
    
    def __str__(self):
        return self.title


class Content(models.Model):
    module = models.ForeignKey(Module,related_name='contents',on_delete=models.CASCADE)
    
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            "model__in":(
                'text',
                'video',
                'image',
                'file'
            )
        }
    ) #
    
    object_id = models.PositiveIntegerField()

    item = GenericForeignKey(
        'content_type',
        'object_id'
    )
    


class ItemBase(models.Model):
    owner = models.ForeignKey(Teacher,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        abstract = True


class Text(ItemBase):
    content = models.TextField() 
    
class File(ItemBase):
    file = models.FileField(upload_to='files')


class Video(ItemBase):
    url = models.URLField()
    
    @property
    def embed_url(self):
        if "youtube.com/watch?v=" in self.url:
            return self.url.replace("watch?v=", "embed/")
        if "youtu.be/" in self.url:
            return self.url.replace("youtu.be/", "youtube.com/embed/")
        return self.url

class Image(ItemBase):
    image = models.ImageField(upload_to='images')

upskill/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView,TemplateView,DetailView
from .models import Subject,Course,Module, Content


import os
from django.http import FileResponse, Http404
from django.shortcuts import get_object_or_404
from .models import File, Content
# Create your views here.


# def index(request):
#     if request.method == 'POST':
#         pass
    
#     else:
#         pass

#     return render(request,'upskill/index.html')


# class IndexView(View):
    
#     def get(self,request,subject_slug = None):
        
#         if subject_slug is None:
#             subjects = Subject.objects.all()
#         else:
#             pass
    
#         context = {
#             'subjects':subjects.order_by('id')
#         }
        
#         return render(request,'upskill/index.html',context)
    

class IndexView(ListView):
    model = Subject
    template_name = 'upskill/index.html'
    context_object_name = 'subjects'
    ordering = ['id']

    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        
        subject_slug = self.kwargs.get('subject_slug')
        
        courses = Course.objects.all()
        
        if subject_slug:
            courses = courses.filter(subject__slug = subject_slug)
        
        context['courses'] = courses
        
        
        return context
    
    
class AboutView(TemplateView):
    template_name = 'upskill/about.html'



class CourseView(TemplateView):
    template_name = 'upskill/course.html'
    
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['courses'] = Course.objects.all()
        return context
    
    
class CourseDetail(DetailView):
    template_name = 'upskill/detail.html'
    queryset = Course.objects.all()
    context_object_name = 'course'

    def get_context_data(self, **kwargs):
        course = self.get_object()
        context =  super().get_context_data(**kwargs)
        context['modules'] = enumerate(course.modules.all(), start=1)
        return context
    

    

class ContentDetailView(DetailView):
    template_name = 'upskill/content_detail.html'
    context_object_name = 'content'
    model = Content
    



def download_file(request, content_id):
    content = get_object_or_404(Content, id=content_id)

    # faqat file bo‘lsa
    if content.content_type.model != 'file':
        raise Http404("Not a file content")

    file_item = content.item  # bu File model

    file_path = file_item.file.path
    file_name = os.path.basename(file_path)

    response = FileResponse(
        open(file_path, 'rb'),
        as_attachment=True,
        filename=file_name
    )
    return response

upskill/templates/upskill/base/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Upskill</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'upskill/img/logo.png' %}" rel="icon" type="image/png">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'upskill/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'upskill/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid bg-dark">
        <div class="row py-2 px-lg-5">
            <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center text-white">
                    <small><i class="fa fa-phone-alt mr-2"></i>+998978184848</small>
                    <small class="px-3">|</small>
                    <small><i class="fa fa-envelope mr-2"></i>jamoliddinabdugafforov7@gamail.com</small>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5">
            <a href="{% url 'upskill:index' %}" class="navbar-brand ml-lg-3">
                <h1 class="m-0 text-uppercase text-primary"><i class="fa fa-book-reader mr-3"></i>Upskill</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mx-auto py-0">
                    <a href="{% url 'upskill:index' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'upskill:about' %}" class="nav-item nav-link">About</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Subjects</a>
                        <div class="dropdown-menu m-0">
                            {% for subject in subjects%}
                                <a href="{% url 'upskill:courses_of_subject' subject.slug %}" class="dropdown-item">{{subject.title}}</a>
                            {%endfor%}
                        </div>
                    </div>
                    <a href="{% url 'upskill:courses' %}" class="nav-item nav-link">Courses</a>
                    
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu m-0">
                            <a href="feature.html" class="dropdown-item">Our Features</a>
                            <a href="team.html" class="dropdown-item">Instructors</a>
                            <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                        </div>
                    </div>
                    {% comment %} <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a> {% endcomment %}
                </div>
                {%if user.is_authenticated%}
                
                <form method="post" action="{% url 'user:logout' %}">
                    {% csrf_token %}
                    <div class="d-flex align-items-center gap-4">
                        <span style="font-size:20px; font-weight:600;">
                            {{ user.email }}
                        </span>

                        <button class="btn btn-primary py-2 px-4 d-none d-lg-block">
                            SignOut
                        </button>
                    </div>
                    
                </form>
                {%else%}
                    <a href="{% url 'user:register_page' %}" class="btn btn-primary py-2 px-4 d-none d-lg-block">SignUp</a>
                {%endif%}
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid page-header position-relative overlay-bottom" style="margin-bottom: 90px;">
        <div class="container text-center py-5">
            <h1 class="text-white display-1">{%block mainPage%}{%endblock%}</h1>
            <div class="d-inline-flex text-white mb-5">
                <p class="m-0 text-uppercase"><a class="text-white" href="{% url 'upskill:index'%}">Home</a></p>
                <i class="fa fa-angle-double-right pt-1 px-3"></i>
                <p class="m-0 text-uppercase">{%block variablePath%} {%endblock%}</p>
            </div>
            <div class="mx-auto mb-5" style="width: 100%; max-width: 600px;">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-light bg-white text-body px-4 dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Courses</button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Courses 1</a>
                            <a class="dropdown-item" href="#">Courses 2</a>
                            <a class="dropdown-item" href="#">Courses 3</a>
                        </div>
                    </div>
                    <input type="text" class="form-control border-light" style="padding: 30px 25px;" placeholder="Keyword">
                    <div class="input-group-append">
                        <button class="btn btn-secondary px-4 px-lg-5">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->


    {%block index_content%}
    {% endblock %}

    {%block about_content %}
    {%endblock%}

    {%block course_content %}
    {%endblock%}

    {%block course_detail%}
    {%endblock%}

    <!-- Footer Start -->
    <div class="container-fluid position-relative overlay-top bg-dark text-white-50 py-5" style="margin-top: 90px;">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <a href="index.html" class="navbar-brand">
                        <h1 class="mt-n2 text-uppercase text-white"><i class="fa fa-book-reader mr-3"></i>Upskill</h1>
                    </a>
                    <p class="m-0">Accusam nonumy clita sed rebum kasd eirmod elitr. Ipsum ea lorem at et diam est, tempor rebum ipsum sit ea tempor stet et consetetur dolores. Justo stet diam ipsum lorem vero clita diam</p>
                </div>
                <div class="col-md-6 mb-5">
                    <h3 class="text-white mb-4">Newsletter</h3>
                    <div class="w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary px-4">Sign Up</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Get In Touch</h3>
                    <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                    <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                    <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
                    <div class="d-flex justify-content-start mt-4">
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-twitter"></i></a>
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-facebook-f"></i></a>
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-linkedin-in"></i></a>
                        <a class="text-white" href="#"><i class="fab fa-2x fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Our Courses</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Web Design</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Apps Design</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Marketing</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Research</a>
                        <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>SEO</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Quick Links</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Privacy Policy</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Terms & Condition</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Regular FAQs</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Help & Support</a>
                        <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>Contact</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white-50 border-top py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
                    <p class="m-0">Copyright &copy; <a class="text-white" href="#">Your Site Name</a>. All Rights Reserved.
                    </p>
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <p class="m-0">Designed by <a class="text-white" href="https://htmlcodex.com">HTML Codex</a> Distributed by <a href="https://themewagon.com" target="_blank">ThemeWagon</a></p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary rounded-0 btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'upskill/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'upskill/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'upskill/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'upskill/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'upskill/js/main.js' %}">
    </script>
</body>

</html>