config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('upskill/',include('upskill.urls',namespace='upskill')),
    path('user/',include('user.urls',namespace='user')),
    path('social-auth/', include('social_django.urls', namespace='social')),

] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import register_page,verify_email_confirm
from django.contrib.auth.views import LogoutView


app_name = 'user'

urlpatterns = [
    path('register/',register_page,name='register_page'),
    path('email-confirm/<uidb64>/<token>/',verify_email_confirm,name='verify-email-confirm'),
    path('logout/',LogoutView.as_view(),name='logout')
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.email

    

user/forms.py
from django import forms
from .models import CustomUser



class RegisterForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")
    
    class Meta:
        model = CustomUser
        fields = ['email','password','confirm_password']
        
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if CustomUser.objects.filter(email = email).exists():
            raise forms.ValidationError(f"{email} already exists!")
    
        return email


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError('Password did not match')
        
        return cleaned_data

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib import messages
from django.http import HttpResponse
from .models import CustomUser
from django.contrib.auth import login
# Create your views here.




def register_page(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.is_active = False
            user.save()
            
            # activation link
            current_site = get_current_site(request) # http://127.0.0.1/
            email = user.email
            subject = "Verify Email"
            message = render_to_string('user/verify_email_message.html', {
                'request': request,
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            }
            )
            
            email = EmailMessage(
                subject, message, to=[email]
            )
            email.content_subtype = 'html'
            email.send()
           
            return HttpResponse('Please, verify your gmail')
        
            
    return render(request,'user/register.html',{'form':form})   



def verify_email_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    
    print('----------------------')
    print(user)
    print('----------------------')
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        
        login(request,user , backend='django.contrib.auth.backends.ModelBackend')        
        return redirect('upskill:index')
    else:
        messages.warning(request, 'The link is invalid.')
        return HttpResponse('Oops, smth is wrong')
      
      

user/templates/user/verify_email_message.html
<div style="background-color: #c2c2c2; padding: 15px;">
    <h2 style="margin: 0; padding: 10px; border-top-left-radius: 10px; border-top-right-radius: 10px; background-color: #5865F2; color: #ffffff;">Verify Email</h2>
    <div style="margin: 0; padding: 15px; background-color: #ffffff;">
        <p>Hi {{ user.name }},</p>
        <p>You created an account on Delight.com, you need to verify your email. Please click on the button below to verify your email.</p>
        <a href="{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}" style="border: 0; color: #ffffff; background-color: #5865F2; padding: 15px; font-weight: bold; text-decoration: none; border-radius: 5px;">
            Verify Email
        </a>
        <p style="margin-top: 40px;">Or you can copy the link below to your browser</p>
        <p>{{ request.scheme }}://{{ domain }}{% url 'user:verify-email-confirm' uidb64=uid token=token %}</p>
        <p>The Delight Team</p>
    </div>
    <div style="text-align: center; margin-top: 20px 0;">
        <p>© {% now 'Y' %} <a href="https://delighto.medium.com">Blog</a></p>
        <p>Follow us on <a href="https://twitter.com/DelightGbolahan">Twitter</a></p>
    </div>
</div>